### ISSUE TITLE
Example Launch File/How to Use

### ISSUE THREAD

**Issue by superjax** [byu-magicc/fcu_io#1]
Hey @dpkoch, I want to write a little more on the ground station.  Specifically, i want to implement the services of fcu_io2 and have some basic functionality on the website to set and request parameters.  However, I'm not super familiar with MAVlink, and how it works.  Do you think you could write a little bit on how to use fcu_io2?

**Comment by dpkoch** [comment]
Wrote a quick wiki page describing the parameters, topics, and service requests. See the note at the top, but I'm not sure it's quite ready for integrating with the GCS. Specifically, there's not yet a way for another application to retrieve the actual parameter values; they currently only print to ROS_INFO. I'll work on that as soon as I have some time.

**Comment by dpkoch** [comment]
You can get the parameter setting and saving working as is, just not getting the names or values...

**Comment by superjax** [comment]
Awesome.  Thanks.

By the way, I don't seem to be able to get a heartbeat.  Any ideas?

**Comment by superjax** [comment]
I'm stupid.  Forgot to disconnect the reset pin.
