### ISSUE TITLE
fcu_io2 fails to build

### ISSUE THREAD

**Issue by dallinbriggs** [byu-magicc/fcu_io#17]
I can't seem to find what ParamRequestList.h file this is talking about in fcu_io.h. I haven't seen any recent changes in the commits that would suddenly cause this to fail, so it's likely just me not having an extra package or something. But in case this got deleted, I'm just letting everyone know that this should probably be fixed.

fcu_io2/include/fcu_io.h:24:37: fatal error: fcu_io/ParamRequestList.h: No such file or directory
 #include <fcu_io/ParamRequestList.h>

**Comment by superjax** [comment]
Oh, do you know what.  That is my fault.  I took `message_generation` out of the build dependancies, because I moved the messages to `fcu_common`.  I'll fix it tomorrow morning.
