### ISSUE TITLE
/param_write doesn't always work

### ISSUE THREAD

**Issue by superjax** [byu-magicc/fcu_io#39]
Sometimes, /param_write doesn't work.  In fact, most of the time it doesn't work.  I've seen some cases where calling /param_write returns `True` but fcu_io doesn't actually do anything, and I've seen cases where I the paramters from the temperature calibration don't get saved because the parameters weren't written.  It also sometimes works, but without a confirmation from fcu_io in the terminal

**Comment by superjax** [comment]
Did some digging, it turns out that if RC and the motors aren't plugged in, somehow the FCU is getting armed...  Different problem.

**Comment by dpkoch** [comment]
@superjax So is this issue closed then? Resolved by you preventing the FCU from arming on startup under those conditions?

**Comment by superjax** [comment]
Yeah.  That seems to be the problem.  I'll re-open this if I see it again.
