### ISSUE TITLE
Some general enquiries 

### ISSUE THREAD

**Issue by seanxsj** [byu-magicc/fcu_io#43]
![image](https://cloud.githubusercontent.com/assets/22044733/18522104/42ed4c3a-7ae1-11e6-9e5a-ec5f3d1e4495.png)

**Comment by superjax** [comment]
Hi Sean,

Have you been able to flash the custom firmware to the naze32?  Try looking in the wiki of the ROSflight repo, it has instructions for installing the toolchain required to build the ROSflight source code and flash it to  a naze32.  Once it is flashed, then all you have to do is plug in the naze32 to the computer and run fcu_io.  You'll be able to access the information you are looking for that way.

**Comment by seanxsj** [comment]
Hi, thank you for the reply, I will definitely try it out. Currently the naze 32 is not flashed with the customised firmware. My Ubuntu is mounted on the parallel desktop and it has issues with USB port regelation, I am still trying to get it fixed.  Once again thank you for the excellent work!
